import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import {pathToFileURL} from "node:url";
const out=path.resolve(".sites-runtime/resume-tests");await fs.mkdir(out,{recursive:true});
async function compile(file,target,replacements={}) {let source=await fs.readFile(file,"utf8");for(const [a,b] of Object.entries(replacements)) source=source.replaceAll(a,b);const result=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}});await fs.writeFile(path.join(out,target),result.outputText);}
await compile("lib/resume/model.ts","model.mjs");await compile("lib/resume/analyze.ts","analyze.mjs",{'"./model"':'"./model.mjs"'});await compile("lib/resume/export.ts","export.mjs",{'"./model"':'"./model.mjs"'});
const {blankResume,resumeSchema,newItem,resumeText}=await import(pathToFileURL(path.join(out,"model.mjs")));const {analyzeResume}=await import(pathToFileURL(path.join(out,"analyze.mjs")));const {exportPdf,exportDocx}=await import(pathToFileURL(path.join(out,"export.mjs")));
const r=blankResume();assert.equal(analyzeResume(r).score,0,"Empty resume should not look ready.");
r.basics={name:"José Candidate",headline:"Software Engineer",email:"candidate@example.test",phone:"+91 12345 67890",location:"Chennai, India",linkedin:"https://www.linkedin.com/in/example",website:"https://example.test"};r.summary="Software engineer building reliable Python APIs and React applications. Experienced in collaborative development, tests, and delivery.";r.skills="Python, React, SQL, Git";r.sections[0].items=[{...newItem(),title:"Software Engineer",organisation:"Example Company",start:"Jan 2024",end:"Sep 2026",bullets:["Built 12 Python APIs with documented contracts and tests.","Improved reporting workflows with SQL and reviewed changes with the team."]}];r.sections[1].items=[{...newItem(),title:"B.Tech Computer Science",organisation:"Example University",start:"2020",end:"2024",bullets:["Studied data structures, networks, and software engineering."]}];r.jobDescription="Required: Python, React, Docker, REST APIs. Preferred: SQL and communication.";
assert.ok(resumeSchema.safeParse(r).success);assert.ok(!resumeSchema.safeParse({...r,basics:{...r.basics,website:"javascript:alert(1)"}}).success);assert.ok(!resumeSchema.safeParse({...r,sections:[r.sections[0],r.sections[0]]}).success);
const analysis=analyzeResume(r);assert.ok(analysis.keywords.find(k=>k.term==="Python")?.matched);assert.equal(analysis.keywords.find(k=>k.term==="Docker")?.matched,false);assert.ok(analysis.score>analyzeResume(blankResume()).score);assert.ok(!resumeText(r).includes("Docker"));
const regular=await fs.readFile("public/fonts/LiberationSans-Regular.ttf"),bold=await fs.readFile("public/fonts/LiberationSans-Bold.ttf"),fontBytes=[regular.buffer.slice(regular.byteOffset,regular.byteOffset+regular.byteLength),bold.buffer.slice(bold.byteOffset,bold.byteOffset+bold.byteLength)];
for(const template of ["classic","technical","executive"]) for(const pageSize of ["A4","Letter"]){const result=await exportPdf({...r,template,pageSize},fontBytes);assert.ok(result.pages>=1);assert.ok(result.bytes.byteLength>10000);await fs.writeFile(path.join(out,`${template}-${pageSize}.pdf`),result.bytes);await fs.writeFile(path.join(out,`${template}-${pageSize}.expected.txt`),result.expectedText);}
const long=structuredClone(r);long.sections[0].items=Array.from({length:35},(_,i)=>({...newItem(),title:"Role "+i,organisation:"Example Company",start:"Jan 2020",end:"Jan 2021",bullets:["Built reliable software and collaborated on documented project work."]}));const pages=await exportPdf(long,fontBytes);assert.ok(pages.pages>1,"Long resumes must paginate.");await fs.writeFile(path.join(out,"long.pdf"),pages.bytes);await fs.writeFile(path.join(out,"long.expected.txt"),pages.expectedText);
const word=await exportDocx(r);await fs.writeFile(path.join(out,"resume.docx"),new Uint8Array(await word.arrayBuffer()));
console.log("Resume schema, scores, keyword gaps, all 6 template/page combinations, pagination, and DOCX generation passed.");
